name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-messages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: kaste/upgrade-messages-test-action@v1

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: TrueBrain/actions-flake8@v2

  mypy:
    strategy:
      fail-fast: false
      matrix:
        platform: ['linux', 'darwin', 'win32']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install mypy
      run: |
        pip install mypy
    - name: Check with mypy
      run: |
        mypy . --platform=${{ matrix.platform }}

  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: SublimeText/UnitTesting/actions/setup@v1
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
